<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="Mymoon" failures="1" tests="1" name="Default test" time="17.533" errors="0" timestamp="08 Aug 2023 12:59:20 GMT">
  <testcase classname="testclass.SampleTestclass" name="loginWithInvalidDetails" time="10.425">
    <failure type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:60)
	at utils.Reporter.reportStep(Reporter.java:70)
	at utils.SeMethods.locateElement(SeMethods.java:103)
	at pages.LoginPage.closeicon(LoginPage.java:21)
	at testclass.SampleTestclass.loginWithInvalidDetails(SampleTestclass.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginWithInvalidDetails -->
  <testcase classname="testclass.SampleTestclass" name="checkCartwithoutLogin" time="0.0">
    <ignored/>
  </testcase> <!-- checkCartwithoutLogin -->
  <testcase classname="testclass.SampleTestclass" name="checkCartAfterAddedProduct" time="0.0">
    <ignored/>
  </testcase> <!-- checkCartAfterAddedProduct -->
  <testcase classname="testclass.SampleTestclass" name="loginWithValidDetails" time="0.0">
    <ignored/>
  </testcase> <!-- loginWithValidDetails -->
  <testcase classname="testclass.SampleTestclass" name="checkCartBeforeAddedProduct" time="0.0">
    <ignored/>
  </testcase> <!-- checkCartBeforeAddedProduct -->
  <testcase classname="testclass.SampleTestclass" name="SearchProduct" time="0.0">
    <ignored/>
  </testcase> <!-- SearchProduct -->
  <testcase classname="testclass.SampleTestclass" name="AddToCart" time="0.0">
    <ignored/>
  </testcase> <!-- AddToCart -->
</testsuite> <!-- Default test -->
